version: '3'

services:
  keycloak:
    container_name: youinq-keycloak
    image: quay.io/keycloak/keycloak:20.0.5
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8080:8080
    volumes:
      - ./themes/youinq:/opt/keycloak/themes/youinq
